#!/usr/bin/zsh

# Disable accessibility bus
export NO_AT_BRIDGE=1

picom --experimental-backends &
redshift &

# Keyboard
xset r rate 206 55
setxkbmap -layout us,ru -option grp:caps_toggle

# Cursor
xsetroot -cursor_name left_ptr

# Xresources
xrdb -merge "${XDG_CONFIG_DIR}/X11/xresources"

export WALLPAPER=~/pictures/michelle-spollen-c9MFM8rSMsQ-unsplash.jpg
feh --no-fehbg --bg-fill $WALLPAPER

# xss-lock -- i3lock -i ${WALLPAPER} &
# loginctl lock-session

sxhkd -m -1 &
polybar main &
