#!/usr/bin/zsh

# Disable accessibility bus
export NO_AT_BRIDGE=1

picom --experimental-backends &
redshift &

xset r rate 206 55
xsetroot -cursor_name left_ptr

export WALLPAPER=~/pictures/michelle-spollen-c9MFM8rSMsQ-unsplash.jpg
feh --no-fehbg --bg-fill $WALLPAPER

# xss-lock -- i3lock -i ${WALLPAPER} &
# loginctl lock-session

sxhkd -m -1 &
polybar main &
