#!/usr/bin/zsh

bspc config split_ratio               0.52
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config single_monocle            false
bspc config focus_follows_pointer     true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc monitor -d {1..10}
